# Generated by Django 2.0.7 on 2018-07-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiztrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_category1', models.CharField(blank=True, max_length=50)),
                ('question_category2', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_category1',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
