# Generated by Django 2.0.7 on 2018-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiztrans', '0002_auto_20180730_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category2',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
