# Generated by Django 2.0.7 on 2018-09-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiztrans', '0004_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
