# Generated by Django 2.0.7 on 2018-09-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiztrans', '0005_auto_20180908_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_md',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_my',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ta',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
