# Generated by Django 2.0.7 on 2018-09-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiztrans', '0006_auto_20180909_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.FloatField(default=0),
        ),
    ]
